---
require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - "bin/**/*"
    - "log/**/*"
    - "db/schema.rb"
    - "public/**/*"
    - "script/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
  Include:
    - "**/Gemfile"
    - "**/Rakefile"
    - "**/Capfile"
    - "**/config.ru"
    - "**/*.rb"
  NewCops: enable
  SuggestExtensions: false

Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Layout/LineLength:
  Enabled: false
  Max: 120

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/EmptyFile:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false # buggy

Lint/RaiseException:
  Enabled: true

Lint/RedundantSafeNavigation:
  Enabled: false

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 50

Metrics/ModuleLength:
  Max: 200

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 12

Naming/BlockForwarding:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Performance/AncestorsInclude:
  Enabled: true

Performance/ArraySemiInfiniteRangeSlice:
  Enabled: false

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Rails:
  Enabled: true

Rails/BulkChangeTable:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/Output:
  AutoCorrect: false

Rails/NotNullColumn:
  Enabled: false

Rails/PluckId:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/UnknownEnv:
  Enabled: false

Rails/WhereEquals:
  Enabled: false

# Disabled unless rubocop-rspec is installed and included above
#
# RSpec/DescribedClass:
#   Enabled: false
#
# RSpec/ExampleLength:
#   Enabled: false
#
# RSpec/ExpectChange:
#   EnforcedStyle: block
#
# RSpec/MessageSpies:
#   EnforcedStyle: receive
#
# RSpec/MultipleExpectations:
#   Enabled: false
#
# RSpec/NestedGroups:
#   Max: 4

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FormatStringToken:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: false

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true

Style/StringConcatenation:
  Enabled: false
